name: 提交新规则（JSON）
description: 借助应用内的复制设置功能来提交规则
body:
  - type: markdown
    attributes:
      value: |
        感谢使用并向第三方“存储空间隔离”在线规则提交新规则！
        为了更迅速的处理规则请求，请仔细阅读填写说明并正确填写。
  - type: checkboxes
    id: rule-status
    attributes:
      label: 规则状态
      options:
        - label: 规则已存在
          required: true
  - type: textarea
    attributes:
      label: 设置 JSON：
      placeholder: 轻触应用内的“上传图标”（于 v4.3.0 版本添加），轻触“复制当前设置到剪贴板”并粘贴到这里。
      render: shell
    validations:
      required: true
  - type: textarea
    id: Necessary-information
    attributes:
      label: 补充必要的信息：
      placeholder: |
        1. 如果现有的规则存在错误，请指出。
        2. 如果隔离后存在部分功能无法使用或有特别的注意事项，请说明。
        3. 如果可以，介绍该应用使用存储空间的行为。
        4. 对“可访问文件夹”规则和“导出被隔离的文件”规则，请说明它们的作用。
    validations:
      required: false
