name: Submit a new rule (JSON)
description: Submit a new rule with in-app copy configuration function
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using and submitting new rules to the third-party "Storage Isolation" online rules!
        In order to process rule requests more quickly, please read the instructions carefully and fill them out correctly.
  - type: checkboxes
    id: rule-status
    attributes:
      label: Rule status
      options:
        - label: Rule already exists
          required: true
  - type: textarea
    attributes:
      label: "Configuration JSON:"
      placeholder: Tap in-app "upload icon" (added from v4.3.0), "Copy current settings to clipboard" and then paste to below.
      render: shell
    validations:
      required: true
  - type: textarea
    id: Necessary-information
    attributes:
      label: "Necessary information:"
      placeholder: |
        1. If there are errors in the existing rules, please indicate.
        2. If there are some functions not work after isolation or there are special notes, please explain.
        3. If possible, describe the behavior of using storage.
        4. To "Accessible folders" rules and "Export isolated files" rules, please explain their role.
    validations:
      required: false
